export default [
  "Being too cool",
  "Being too hot",
  "Being too awesome",
  "Being too sexy",
  "Being too smart",
  "Being too dumb",
  "Being too funny",
  "Being too serious",
  "Being too kind",
  "Being too mean",
  "Being too tall",
  "Being too short",
  "Being too strong",
  "Being too weak",
  "Being too fast",
  "Being too slow",
  "Being too rich",
  "Being too poor",
  "Being too healthy",
  "Being too sick",
  "Being too happy",
  "Being too sad",
  "Being too good",
  "Being too bad",
  "Being too ugly",
  "Being too beautiful",
  "Being too old",
  "Having too much hair",
  "Having too much money",
  "Having too much time",
  "Having too much fun",
  "Having too much sex",
  "Having too much food",
  "Having too much water",
  "Not spending enough time with family",
  "Not spending enough time with friends",
  "Not spending enough time with pets",
  "Not spending enough time with plants",
  "Not spending enough time with yourself",
  "Not spending enough time with your partner",
  "Not spending enough time with your kids",
  "Not spending enough time with your parents",
  "Not spending enough time with your siblings",
  "Not spending enough time with your grandparents",
];
